name: checkout code
on:
 push:
  branches:
    - main
 pull_request:
    types: [opened]
  branches:
    - dev     
    
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }} 
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
     - name: terraform
       run: echo "running terraform commands"
     - name: checkout
       uses: actions/checkout@v4
    
     - uses: hashicorp/setup-terraform@v3
       with:
         terraform_version: "1.1.7"  
     - name: init
       run: terraform init
     - name: format
       run: terraform fmt -recursive
     - name: plan
       run: terraform plan
       if: github.event_name == 'pull_request'
     - name: apply
       run: terraform apply -auto-approve 
       if: github.event_name == 'push'&& github.ref == 'ref/head/main' 

  