name: release workflow

on:
  workflow_dispatch:
    
jobs:
   release:
      permissions:
        contents: write
        issues: write
        pull_request: write
    
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: install node
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: modules
          run: npm install semantic-release @semantic-release/git @semantic-release/github -D
        - name: semantic release 
          run: npx semantic-release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      